### ISSUE TITLE
Падает после нажатия кнопки Button

### ISSUE THREAD

**Issue by DimonDeveloper** [OlehKulykov/LzmaSDK-ObjC#1]
![screen shot 2015-11-14 at 8 58 13 pm](https://cloud.githubusercontent.com/assets/3527457/11165241/7dfba84a-8b12-11e5-9474-7c58bebadcce.png)

**Comment by OlehKulykov** [comment]
Да, тип fileURL был assign что привело к потере указателя.
Используйте версию 0.0.4
